### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by Lordog** [princeton-nlp/intercode#10]
I want to access the json results of trajectories of the bash dataset.
However, the `.data/results` directory, which should have contains experiment results, is missed. And googledrive link does not contain files of the bash dataset. And `./data/docker/bash_scripts/setup_nl2b_fs_*.sh`, which should have contained file system definition, is missed too(:
Would you please provide me with json results of trajectories of the bash dataset? Or the setup_nl2b_fs_*.sh, which would help me reproduce the results?

**Comment by john-b-yang** [comment]
Hi @Lordog are you referring to this [folder](https://github.com/princeton-nlp/intercode/tree/master/data/results/bash)? This contains all the trajectories of model performances on the InterCode-Bash task.

Also, the `setup_nl2b_fs_*.sh` should be available in this [folder](https://github.com/princeton-nlp/intercode/tree/master/docker/bash_scripts).

Hope this helps! I will close this issue by Friday if there's no follow up.
