### ISSUE TITLE
Is this repo abandoned?

### ISSUE THREAD

**Issue by kmheckel** [princeton-nlp/intercode#22]
@john-b-yang I Just wanted to know before I invest time trying to see if it's still up to date and spinning up a huggingface endpoint to eval a model.

Thanks!

**Comment by john-b-yang** [comment]
Hi @kmheckel, it's not abandoned! I don't have too much time these days to do big overhauls of the repo, but happy to help with things like using the repo and debugging!

**Comment by kmheckel** [comment]
Thanks - wasn't sure because it looks like the OpenAI API has slightly changed and that the necessary fixes are on another fork that's almost 60 commits ahead of main: https://github.com/princeton-nlp/intercode/commit/99d8863f3e385da7dd7f408cf30677db830d55ef
