### ISSUE TITLE
Why are the leaderboards empty?

### ISSUE THREAD

**Issue by zhimin-z** [princeton-nlp/intercode#23]
![image](https://github.com/princeton-nlp/intercode/assets/8592144/ec631e22-cc0b-4d04-b60e-c05ef15e25da)
![image](https://github.com/princeton-nlp/intercode/assets/8592144/5134a75d-c55e-4243-86a2-0548f2d66de7)
Check https://intercode-benchmark.github.io/#ctf and https://intercode-benchmark.github.io/#swe

**Comment by john-b-yang** [comment]
Afaik, no one has submitted to these leaderboards.

I'll probably deprecate the SWE one soon. The idea behind that has taken on a life of its own in the form of the [SWE-bench](https://www.swebench.com/) + [SWE-agent](https://swe-agent.com/) projects.
