### ISSUE TITLE
Results of eval_n_turn

### ISSUE THREAD

**Issue by shenao-zhang** [princeton-nlp/intercode#7]
Hi,

Thanks for your contribution and the excellent benchmark! But the results when running eval_n_turn with gpt 3.5 and n=10 don't match the TryAgain baseline reported in your paper Table 2. I tested in the Bash environment, and the success rate in Bash 2 is 15%. Is it due to the internal changes in openai api? eval_n_turn with gpt 3.5 and n=20 roughly matches the results in your paper that uses n=10.

Best,
Shenao

**Comment by john-b-yang** [comment]
Hi Shenao,

Thanks for your interest in our repo and kind words! My guess is what you said - perhaps there are internal changes that affect this. The [`data/results/`](https://github.com/princeton-nlp/intercode/tree/master/data/results) folder contains logs from our experiments, and we used these logs to calculate the numbers in this paper. Those results are the best reflection of our observations when we evaluated GPT 3.5 and other LMs on InterCode.

Hope this helps!
John

**Comment by shenao-zhang** [comment]
Dear John,

Thanks for your reply! That makes sense. But the results drop significantly in the Bash environment (not in SQL) using GPT-3.5-turbo, e.g. from 50% to 15% success rate in Base 2. So I'm not sure if the internal changes in API led to this. If you have time to retest TryAgain-GPT-3.5 in Bash, could you please let me know if the results change? Closing the issue for now.

Best,
Shenao
