### ISSUE TITLE
setup error

### ISSUE THREAD

**Issue by yuchenlin** [princeton-nlp/intercode#8]
Hi John,

Thanks for the great work. I'm following the [steps](https://github.com/princeton-nlp/intercode#-build-from-source) of building from source and have such an error, when I run `python run_demo.py sql`

```
Traceback (most recent call last):
  File "/net/nfs2.mosaic/yuchenl/intercode/run_demo.py", line 7, in <module>
    from experiments.policies import HumanPolicy
  File "/net/nfs2.mosaic/yuchenl/intercode/experiments/policies.py", line 5, in <module>
    from .utils import ACTION_PARSER_MAP, PROMPT_MAP, CompletionGPT, ChatGPT, PalmChat, PalmCompletion, HFChat
  File "/net/nfs2.mosaic/yuchenl/intercode/experiments/utils/__init__.py", line 16, in <module>
    from .palm_api import (
  File "/net/nfs2.mosaic/yuchenl/intercode/experiments/utils/palm_api.py", line 15, in <module>
    assert(api_key != None)
AssertionError
```

btw, I also found that `rpyc` is not part of the requirements so that I have to install it. (a minor issue)

**Comment by yuchenlin** [comment]
it seems to require a PALM api key but i'm not sure if this is a must?

**Comment by jmanhype** [comment]
A suggestion if this implementation is too time consuming - maybe you could just write an API that InterCode exposes that mimics CodeBox in this repo:

https://github.com/shroominic/codeinterpreter-api

That would give it the awesome advantage of running LLM/LangChain generated code privately on a local device inside a Docker container in an InterCode environment instead of in the cloud.

What do you think?

**Comment by john-b-yang** [comment]
@yuchenlin Thanks for the issue, and apologies about the delay in response.

Regarding the original issue, you're correct. I have done the following to make onboarding easier:
- Removed the `assert` calls that were throwing the original error (they required Palm, GPT-4 API to be installed, which is unnecessary)
- Added instructions in the `README.md` about installing keys to run experiments
- Added `rpyc` to `environment.yml`

Thanks for the suggestion @jmanhype, I see a similar one has been posted in #2. I will continue to address your point in that thread.

Closing this issue for now, feel free to re-open if there are any follow ups. Thanks again @yuchenlin for issue, and hope you are finding InterCode helpful!

**Comment by yuchenlin** [comment]
Thank you!
